window:
  padding:
    x: 6
    y: 6

font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic
  bold_italic:
    family: Fira Code
    style: Bold Italic
  size: 14

import:
  # uncomment the flavour you want below:
  - ~/.config/alacritty/catppuccin-mocha.yml
#  - ~/.config/alacritty/catppuccin-macchiato.yml
#  - ~/.config/alacritty/catppuccin-frappe.yml
#  - ~/.config/alacritty/catppuccin-latte.yml
